type = "webpack"
account_id = "1b47c0ee9640c245ba237fa508e0178b"
zone_id = "35a008a1d397befed2cf27cf2255433a"
name = "ipv6-tools"

[env.staging]
name = "ipv6-tools-staging"
route = "staging-tools.as211562.net/*"

[env.production]
route = "tools.as211562.net/*"
